<a href="https://colab.research.google.com/github/Anik-1802021/New-Denoising-Idea/blob/main/Denoising_Idea_v_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from PIL import Image

# Load images
image1 = Image.open("/content/NORMAL-153950-1.jpeg").convert('L')  # Ensure images are grayscale
image2 = Image.open("/content/NORMAL-153950-2.jpeg").convert('L')
image3 = Image.open("/content/NORMAL-153950-3.jpeg").convert('L')

# Convert images to numpy arrays
image1_array = np.array(image1, dtype=np.int16)  # Use int16 to allow for negative differences
image2_array = np.array(image2, dtype=np.int16)  # Use int16 to allow for negative differences
image3_array = np.array(image3, dtype=np.int16)  # Use int16 to allow for negative differences

# Print the pixel values of the images
print("Image 1 Array:\n", image1_array)
print("\nImage 2 Array:\n", image2_array)
print("\nImage 3 Array:\n", image3_array)

# Calculate the pixel value difference between the two images
pixel_difference_12 = image1_array - image2_array
pixel_difference_23 = image2_array - image3_array
pixel_difference_13 = image1_array - image3_array

# Print the pixel value difference, including negative values
print("\nPixel Value Difference between Image 1 and Image 2 (including negative values):")
print(pixel_difference_12)

print("\nPixel Value Difference between Image 2 and Image 3 (including negative values):")
print(pixel_difference_23)

print("\nPixel Value Difference between Image 1 and Image 3 (including negative values):")
print(pixel_difference_13)

# Calculate the sum of all absolute pixel values of the difference array
absolute_difference_sum_12 = np.sum(np.abs(pixel_difference_12))
absolute_difference_sum_23 = np.sum(np.abs(pixel_difference_23))
absolute_difference_sum_13 = np.sum(np.abs(pixel_difference_13))

# Print the sum of absolute pixel values
print("\nSum of all absolute pixel values of the difference array_12:")
print(absolute_difference_sum_12)
print("\nSum of all absolute pixel values of the difference array_23:")
print(absolute_difference_sum_23)
print("\nSum of all absolute pixel values of the difference array_13:")
print(absolute_difference_sum_13)

# Determine which image is the most dissimilar
sums = {
    'image1_image2': absolute_difference_sum_12,
    'image2_image3': absolute_difference_sum_23,
    'image1_image3': absolute_difference_sum_13
}

most_dissimilar_pair = max(sums, key=sums.get)
most_dissimilar_image = None

if most_dissimilar_pair == 'image1_image2':
    if absolute_difference_sum_23 < absolute_difference_sum_13:
        most_dissimilar_image = 'Image 1'
    else:
        most_dissimilar_image = 'Image 2'
elif most_dissimilar_pair == 'image2_image3':
    if absolute_difference_sum_12 < absolute_difference_sum_13:
        most_dissimilar_image = 'Image 3'
    else:
        most_dissimilar_image = 'Image 2'
elif most_dissimilar_pair == 'image1_image3':
    if absolute_difference_sum_12 < absolute_difference_sum_23:
        most_dissimilar_image = 'Image 3'
    else:
        most_dissimilar_image = 'Image 1'

# Print the most dissimilar image
print(f"\nThe most dissimilar image is: {most_dissimilar_image}")


Image 1 Array:
 [[ 42  43  45 ... 255 255 255]
 [ 36  35  38 ... 255 255 255]
 [ 36  34  39 ... 255 255 255]
 ...
 [255 255 255 ...   5   7   0]
 [255 255 255 ...   4   6   1]
 [255 255 255 ...   2   5   0]]

Image 2 Array:
 [[ 2  0  0 ... 21 10  0]
 [ 0  0  0 ... 16  6 18]
 [ 0  1  1 ... 15  6 21]
 ...
 [ 0  0  0 ...  5  4  2]
 [ 0  0  0 ...  3  2  2]
 [ 2  0  0 ...  1  1  2]]

Image 3 Array:
 [[255 255  43 ... 255 255 255]
 [255 255  41 ... 255 255 255]
 [255 255  41 ... 255 255 255]
 ...
 [255 249 255 ...  12  10   9]
 [254 253 255 ...  16  15  13]
 [255 255 251 ...  12  13  12]]

Pixel Value Difference between Image 1 and Image 2 (including negative values):
[[ 40  43  45 ... 234 245 255]
 [ 36  35  38 ... 239 249 237]
 [ 36  33  38 ... 240 249 234]
 ...
 [255 255 255 ...   0   3  -2]
 [255 255 255 ...   1   4  -1]
 [253 255 255 ...   1   4  -2]]

Pixel Value Difference between Image 2 and Image 3 (including negative values):
[[-253 -255  -43 ... -234 -245 -255]
 [-255 -255  -41 ..

In [2]:
import numpy as np
from PIL import Image

# Load images
image1 = Image.open("/content/NORMAL-153950-1.jpeg").convert('L')  # Ensure images are grayscale
image2 = Image.open("/content/NORMAL-153950-2.jpeg").convert('L')
image3 = Image.open("/content/NORMAL-153950-3.jpeg").convert('L')

# Convert images to numpy arrays
image1_array = np.array(image1, dtype=np.int16)  # Use int16 to allow for negative differences
image2_array = np.array(image2, dtype=np.int16)
image3_array = np.array(image3, dtype=np.int16)

# Print the pixel values of the images
print("Image 1 Array:\n", image1_array)
print("\nImage 2 Array:\n", image2_array)
print("\nImage 3 Array:\n", image3_array)

# Calculate the pixel value difference between the images
pixel_difference_12 = image1_array - image2_array
pixel_difference_23 = image2_array - image3_array
pixel_difference_13 = image1_array - image3_array

# Calculate the sum of all absolute pixel values of the difference array
absolute_difference_sum_12 = np.sum(np.abs(pixel_difference_12))
absolute_difference_sum_23 = np.sum(np.abs(pixel_difference_23))
absolute_difference_sum_13 = np.sum(np.abs(pixel_difference_13))

# Determine which image is the most dissimilar
sums = {
    'image1_image2': absolute_difference_sum_12,
    'image2_image3': absolute_difference_sum_23,
    'image1_image3': absolute_difference_sum_13
}

most_dissimilar_pair = max(sums, key=sums.get)
most_dissimilar_image = None

if most_dissimilar_pair == 'image1_image2':
    if absolute_difference_sum_23 < absolute_difference_sum_13:
        most_dissimilar_image = 'Image 1'
    else:
        most_dissimilar_image = 'Image 2'
elif most_dissimilar_pair == 'image2_image3':
    if absolute_difference_sum_12 < absolute_difference_sum_13:
        most_dissimilar_image = 'Image 3'
    else:
        most_dissimilar_image = 'Image 2'
elif most_dissimilar_pair == 'image1_image3':
    if absolute_difference_sum_12 < absolute_difference_sum_23:
        most_dissimilar_image = 'Image 3'
    else:
        most_dissimilar_image = 'Image 1'

# Print the most dissimilar image
print(f"\nThe most dissimilar image is: {most_dissimilar_image}")

# Denoise the most dissimilar image (image3) using the average of image1 and image2
if most_dissimilar_image == 'Image 3':
    denoised_image3_array = (image1_array + image2_array) // 2
    denoised_image3 = Image.fromarray(denoised_image3_array.astype(np.uint8))

    # Show the denoised image
    denoised_image3.show()

    # Save the denoised image (optional)
    denoised_image3.save("/content/denoised_image3.jpeg")

    # Print the pixel values of the denoised image
    print("\nDenoised Image 3 Array:\n", denoised_image3_array)


Image 1 Array:
 [[ 42  43  45 ... 255 255 255]
 [ 36  35  38 ... 255 255 255]
 [ 36  34  39 ... 255 255 255]
 ...
 [255 255 255 ...   5   7   0]
 [255 255 255 ...   4   6   1]
 [255 255 255 ...   2   5   0]]

Image 2 Array:
 [[ 2  0  0 ... 21 10  0]
 [ 0  0  0 ... 16  6 18]
 [ 0  1  1 ... 15  6 21]
 ...
 [ 0  0  0 ...  5  4  2]
 [ 0  0  0 ...  3  2  2]
 [ 2  0  0 ...  1  1  2]]

Image 3 Array:
 [[255 255  43 ... 255 255 255]
 [255 255  41 ... 255 255 255]
 [255 255  41 ... 255 255 255]
 ...
 [255 249 255 ...  12  10   9]
 [254 253 255 ...  16  15  13]
 [255 255 251 ...  12  13  12]]

The most dissimilar image is: Image 2


In [3]:
import numpy as np
from PIL import Image

# Load images
image1 = Image.open("/content/NORMAL-153950-1.jpeg").convert('L')  # Ensure images are grayscale
image2 = Image.open("/content/NORMAL-153950-2.jpeg").convert('L')
image3 = Image.open("/content/NORMAL-153950-3.jpeg").convert('L')

# Convert images to numpy arrays
image1_array = np.array(image1, dtype=np.int16)  # Use int16 to allow for negative differences
image2_array = np.array(image2, dtype=np.int16)
image3_array = np.array(image3, dtype=np.int16)

# Print the pixel values of the images
print("Image 1 Array:\n", image1_array)
print("\nImage 2 Array:\n", image2_array)
print("\nImage 3 Array:\n", image3_array)

# Calculate the pixel value difference between the images
pixel_difference_12 = image1_array - image2_array
pixel_difference_23 = image2_array - image3_array
pixel_difference_13 = image1_array - image3_array

# Calculate the sum of all absolute pixel values of the difference array
absolute_difference_sum_12 = np.sum(np.abs(pixel_difference_12))
absolute_difference_sum_23 = np.sum(np.abs(pixel_difference_23))
absolute_difference_sum_13 = np.sum(np.abs(pixel_difference_13))

# Determine which image is the most dissimilar
sums = {
    'image1_image2': absolute_difference_sum_12,
    'image2_image3': absolute_difference_sum_23,
    'image1_image3': absolute_difference_sum_13
}

most_dissimilar_pair = max(sums, key=sums.get)
most_dissimilar_image = None

if most_dissimilar_pair == 'image1_image2':
    if absolute_difference_sum_23 < absolute_difference_sum_13:
        most_dissimilar_image = 'Image 1'
    else:
        most_dissimilar_image = 'Image 2'
elif most_dissimilar_pair == 'image2_image3':
    if absolute_difference_sum_12 < absolute_difference_sum_13:
        most_dissimilar_image = 'Image 3'
    else:
        most_dissimilar_image = 'Image 2'
elif most_dissimilar_pair == 'image1_image3':
    if absolute_difference_sum_12 < absolute_difference_sum_23:
        most_dissimilar_image = 'Image 3'
    else:
        most_dissimilar_image = 'Image 1'

# Print the most dissimilar image
print(f"\nThe most dissimilar image is: {most_dissimilar_image}")

# Denoise the most dissimilar image using the average of the other two images
if most_dissimilar_image == 'Image 3':
    denoised_image = (image1_array + image2_array) // 2
elif most_dissimilar_image == 'Image 2':
    denoised_image = (image1_array + image3_array) // 2
else:  # most_dissimilar_image == 'Image 1'
    denoised_image = (image2_array + image3_array) // 2

# Convert the denoised image array back to an image
denoised_image = Image.fromarray(denoised_image.astype(np.uint8))

# Show the denoised image
denoised_image.show()

# Save the denoised image (optional)
denoised_image.save(f"/content/denoised_{most_dissimilar_image.lower()}.jpeg")

# Print the pixel values of the denoised image
print(f"\nDenoised {most_dissimilar_image} Array:\n", denoised_image)


Image 1 Array:
 [[ 42  43  45 ... 255 255 255]
 [ 36  35  38 ... 255 255 255]
 [ 36  34  39 ... 255 255 255]
 ...
 [255 255 255 ...   5   7   0]
 [255 255 255 ...   4   6   1]
 [255 255 255 ...   2   5   0]]

Image 2 Array:
 [[ 2  0  0 ... 21 10  0]
 [ 0  0  0 ... 16  6 18]
 [ 0  1  1 ... 15  6 21]
 ...
 [ 0  0  0 ...  5  4  2]
 [ 0  0  0 ...  3  2  2]
 [ 2  0  0 ...  1  1  2]]

Image 3 Array:
 [[255 255  43 ... 255 255 255]
 [255 255  41 ... 255 255 255]
 [255 255  41 ... 255 255 255]
 ...
 [255 249 255 ...  12  10   9]
 [254 253 255 ...  16  15  13]
 [255 255 251 ...  12  13  12]]

The most dissimilar image is: Image 2

Denoised Image 2 Array:
 <PIL.Image.Image image mode=L size=512x512 at 0x7FD3F034ED10>
